BesselBasis_trainable: true
PolynomialCutoff_p: 6
_jit_bailout_depth: 2
_jit_fusion_strategy:
- !!python/tuple
  - DYNAMIC
  - 3
allow_tf32: true
append: false
ase_args:
  format: extxyz
avg_num_neighbors: 33.2158203125
batch_size: 5
chemical_embedding_irreps_out: 32x0e
chemical_symbols:
- Sb
- Mo
- Te
- Tb
- Hg
- Pm
- Dy
- P
- Pd
- Cd
- Nd
- Ga
- Ho
- Tc
- Np
- Ni
- Mn
- La
- Os
- O
- Y
- Co
- Hf
- Eu
- Sc
- B
- Ce
- Cl
- Rb
- Zr
- Pu
- Er
- Pa
- S
- Ta
- Sm
- Ir
- Ag
- Lu
- Pt
- Cu
- I
- Bi
- Al
- C
- Mg
- K
- Zn
- In
- Br
- Ti
- As
- H
- Fe
- Pr
- V
- Pb
- Tl
- Th
- Ge
- Ca
- W
- Sr
- Ru
- Ba
- Rh
- Re
- Nb
- Tm
- Gd
- Sn
- Se
- Ac
- Cs
- F
- Si
- U
- Be
- Au
- Li
- Na
- N
- Cr
conv_to_output_hidden_irreps_out: 16x0e
dataloader_num_workers: 0
dataset: ASEDataset
dataset_AtomicData_options:
  r_max: 5.0
dataset_file_name: ../data/data_train.extxyz
dataset_seed: null
dataset_statistics_stride: 1
default_dtype: float32
device: cuda
early_stopping: null
early_stopping_kwargs: null
ema_decay: 0.999
ema_use_num_updates: true
end_of_batch_callbacks: []
end_of_epoch_callbacks: []
end_of_train_callbacks: []
equivariance_test: false
exclude_keys: []
feature_irreps_hidden: 32x0e+32x1e+32x2e+32x0o+32x1o+32x2o
final_callbacks: []
grad_anomaly_mode: false
include_keys:
- bader
init_callbacks: []
invariant_layers: 2
invariant_neurons: 64
irreps_edge_sh: 1x0e+1x1o+1x2e
l_max: 2
learning_rate: 0.001
log_batch_freq: 100
log_epoch_freq: 1
loss_coeffs:
  bader:
  - 1
  - L1Loss
  total_energy:
  - 1
  - PerAtomMSELoss
lr_scheduler_kwargs: {}
lr_scheduler_name: none
max_epochs: 1000
max_gradient_norm: .inf
metrics_components: null
metrics_key: validation_loss
model_builders:
- SimpleIrrepsConfig
- chargeModel
- PerSpeciesRescale
- RescaleEnergyEtc
model_debug_mode: false
model_dtype: float32
n_train: 560
n_train_per_epoch: null
n_val: 69
nonlinearity_gates:
  e: silu
  o: tanh
nonlinearity_scalars:
  e: silu
  o: tanh
nonlinearity_type: gate
num_basis: 8
num_features: 32
num_layers: 4
num_types: 83
optimizer_kwargs:
  amsgrad: false
  betas: !!python/tuple
  - 0.9
  - 0.999
  capturable: false
  differentiable: false
  eps: 1.0e-08
  foreach: null
  fused: false
  maximize: false
  weight_decay: 0
optimizer_name: Adam
parity: true
r_max: 5.0
report_init_validation: true
resnet: false
root: ../train_charge
run_id: wZFP7z8TgAKwlZrIDm16YrRAyzrW-geNg5sLFq3VfK4
run_name: charge_train
save_checkpoint_freq: -1
save_ema_checkpoint_freq: -1
seed: 42
shuffle: true
start_of_epoch_callbacks: []
train_idcs: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
    ZQpxAVgJAAAAMTQ0NjY3MzQ0cQJYAwAAAGNwdXEDTTACTnRxBFEugAJdcQBYCQAAADE0NDY2NzM0
    NHEBYS4wAgAAAAAAABYAAAAAAAAA5gAAAAAAAADqAAAAAAAAACgCAAAAAAAABgEAAAAAAAAmAgAA
    AAAAANoBAAAAAAAACwIAAAAAAABOAAAAAAAAAA0BAAAAAAAAWAAAAAAAAADMAAAAAAAAAFYAAAAA
    AAAA6AEAAAAAAADrAQAAAAAAAKsBAAAAAAAAEwEAAAAAAACJAQAAAAAAAIcAAAAAAAAABAEAAAAA
    AACtAQAAAAAAACICAAAAAAAAQwEAAAAAAACNAQAAAAAAAA8AAAAAAAAA/AEAAAAAAABRAQAAAAAA
    AN0AAAAAAAAA1wEAAAAAAACuAAAAAAAAAMAAAAAAAAAA6AAAAAAAAAALAQAAAAAAALcAAAAAAAAA
    gQAAAAAAAACPAQAAAAAAAAcBAAAAAAAAFwAAAAAAAACKAAAAAAAAAB0BAAAAAAAAagAAAAAAAACz
    AAAAAAAAAOUAAAAAAAAAaAAAAAAAAADjAAAAAAAAAHYAAAAAAAAAhwEAAAAAAACoAAAAAAAAAO0A
    AAAAAAAAuwAAAAAAAAD0AQAAAAAAAAkCAAAAAAAAGgIAAAAAAAAnAgAAAAAAAAYAAAAAAAAA4AAA
    AAAAAABvAAAAAAAAACYBAAAAAAAACwAAAAAAAAB8AQAAAAAAAEYBAAAAAAAAxwAAAAAAAADAAQAA
    AAAAADYAAAAAAAAA1gAAAAAAAAAoAAAAAAAAAEMAAAAAAAAAawEAAAAAAAAjAQAAAAAAAAEAAAAA
    AAAAzwAAAAAAAAAoAQAAAAAAANgAAAAAAAAAnAAAAAAAAACwAQAAAAAAABECAAAAAAAAYwAAAAAA
    AAArAgAAAAAAAOYBAAAAAAAAZgAAAAAAAAB2AQAAAAAAAGwBAAAAAAAAwgEAAAAAAABkAQAAAAAA
    AE8AAAAAAAAALAEAAAAAAAAXAQAAAAAAAGgBAAAAAAAAywAAAAAAAADVAAAAAAAAAOcBAAAAAAAA
    4AEAAAAAAAAhAgAAAAAAALcBAAAAAAAA5wAAAAAAAADqAQAAAAAAAOkAAAAAAAAAhAAAAAAAAADB
    AAAAAAAAACEBAAAAAAAAcgEAAAAAAAArAAAAAAAAACsBAAAAAAAA9QAAAAAAAADhAAAAAAAAAJIA
    AAAAAAAAEQAAAAAAAACSAQAAAAAAAGcAAAAAAAAAAgAAAAAAAAAxAQAAAAAAAM4BAAAAAAAA9wEA
    AAAAAAAOAAAAAAAAACIBAAAAAAAAOgAAAAAAAAAYAQAAAAAAABsBAAAAAAAAeQAAAAAAAAAeAgAA
    AAAAAD8BAAAAAAAApQEAAAAAAAAvAgAAAAAAACkBAAAAAAAAiAEAAAAAAACUAQAAAAAAAOEBAAAA
    AAAA7gAAAAAAAACbAAAAAAAAAB0CAAAAAAAARgAAAAAAAAB4AQAAAAAAADQBAAAAAAAAgwEAAAAA
    AABEAQAAAAAAAHABAAAAAAAA0AAAAAAAAACGAQAAAAAAAE4BAAAAAAAAwQEAAAAAAAB6AAAAAAAA
    ABkBAAAAAAAA8wEAAAAAAADkAQAAAAAAAFoAAAAAAAAAhQAAAAAAAABaAQAAAAAAACIAAAAAAAAA
    xAAAAAAAAAARAQAAAAAAADgBAAAAAAAAEAIAAAAAAAANAAAAAAAAAAgBAAAAAAAA8gEAAAAAAADs
    AQAAAAAAAFAAAAAAAAAArwAAAAAAAADWAQAAAAAAADAAAAAAAAAAPAAAAAAAAAAXAgAAAAAAAP8B
    AAAAAAAAEwIAAAAAAACVAAAAAAAAAN8AAAAAAAAAEAAAAAAAAAAnAQAAAAAAAEAAAAAAAAAAVQAA
    AAAAAAAnAAAAAAAAAJ0AAAAAAAAAKgIAAAAAAABLAAAAAAAAAJ8BAAAAAAAAbQAAAAAAAACKAQAA
    AAAAAGQAAAAAAAAAHgAAAAAAAADFAQAAAAAAAGEAAAAAAAAAkQEAAAAAAAA1AAAAAAAAACMCAAAA
    AAAAdAAAAAAAAAAIAAAAAAAAAKcAAAAAAAAAfAAAAAAAAAAOAQAAAAAAAPQAAAAAAAAAygAAAAAA
    AAAIAgAAAAAAAKgBAAAAAAAAhQEAAAAAAAAuAgAAAAAAAOQAAAAAAAAAYQEAAAAAAACiAQAAAAAA
    ALQAAAAAAAAAUAEAAAAAAAC5AAAAAAAAAFEAAAAAAAAAqwAAAAAAAABdAQAAAAAAAF8BAAAAAAAA
    GgEAAAAAAABnAQAAAAAAACoBAAAAAAAAzQEAAAAAAACPAAAAAAAAAIABAAAAAAAAVQEAAAAAAACg
    AQAAAAAAAAICAAAAAAAAqgEAAAAAAAASAgAAAAAAAMMBAAAAAAAA+QAAAAAAAAB4AAAAAAAAADEA
    AAAAAAAA3gEAAAAAAABSAAAAAAAAAGIAAAAAAAAATwEAAAAAAADxAAAAAAAAAF4AAAAAAAAAPgEA
    AAAAAAAAAQAAAAAAAPABAAAAAAAALgEAAAAAAABuAAAAAAAAALEBAAAAAAAA2wEAAAAAAAA7AAAA
    AAAAALoAAAAAAAAARQAAAAAAAABBAQAAAAAAAA4CAAAAAAAA3AEAAAAAAACjAQAAAAAAAGkBAAAA
    AAAApAEAAAAAAAA9AQAAAAAAALIBAAAAAAAA7gEAAAAAAADlAQAAAAAAAK4BAAAAAAAAgQEAAAAA
    AACDAAAAAAAAADQAAAAAAAAApwEAAAAAAAD+AAAAAAAAAB8AAAAAAAAAFgEAAAAAAACMAQAAAAAA
    AAIBAAAAAAAABQAAAAAAAABjAQAAAAAAAHUBAAAAAAAAHwIAAAAAAADMAQAAAAAAANABAAAAAAAA
    aQAAAAAAAADdAQAAAAAAAGsAAAAAAAAAjQAAAAAAAADPAQAAAAAAAAQAAAAAAAAAWQAAAAAAAAB/
    AQAAAAAAAJcBAAAAAAAAcAAAAAAAAACvAQAAAAAAAGAAAAAAAAAApgEAAAAAAADHAQAAAAAAAFsA
    AAAAAAAAcwAAAAAAAADXAAAAAAAAAOIBAAAAAAAA0wEAAAAAAADSAQAAAAAAAG8BAAAAAAAAvQEA
    AAAAAACdAQAAAAAAAAUCAAAAAAAA8wAAAAAAAAD1AQAAAAAAAMMAAAAAAAAA8QEAAAAAAABXAAAA
    AAAAADMBAAAAAAAAhAEAAAAAAACpAQAAAAAAAIsAAAAAAAAApQAAAAAAAAAlAAAAAAAAAPsBAAAA
    AAAABgIAAAAAAADiAAAAAAAAANQAAAAAAAAAPgAAAAAAAAAmAAAAAAAAAIsBAAAAAAAAZQAAAAAA
    AAAsAgAAAAAAACMAAAAAAAAAuAEAAAAAAAB7AQAAAAAAAPkBAAAAAAAAIQAAAAAAAADEAQAAAAAA
    AJMBAAAAAAAACgEAAAAAAACfAAAAAAAAAPwAAAAAAAAAmQAAAAAAAACYAQAAAAAAALEAAAAAAAAA
    AQIAAAAAAACmAAAAAAAAALkBAAAAAAAAeQEAAAAAAABCAQAAAAAAAEkBAAAAAAAAHAAAAAAAAABe
    AQAAAAAAAFQAAAAAAAAAvwEAAAAAAAAFAQAAAAAAAKkAAAAAAAAAUwAAAAAAAAAPAgAAAAAAACAC
    AAAAAAAAXAAAAAAAAACOAQAAAAAAAOsAAAAAAAAA2AEAAAAAAABHAAAAAAAAAIwAAAAAAAAAPwAA
    AAAAAAAvAAAAAAAAAPgAAAAAAAAAbgEAAAAAAAAbAAAAAAAAALwAAAAAAAAABAIAAAAAAAD4AQAA
    AAAAAMYAAAAAAAAAcQEAAAAAAABdAAAAAAAAAK0AAAAAAAAAkAEAAAAAAAC8AQAAAAAAAJMAAAAA
    AAAAxgEAAAAAAADJAQAAAAAAAHoBAAAAAAAAIAEAAAAAAAAKAAAAAAAAAJEAAAAAAAAArAAAAAAA
    AAC/AAAAAAAAAAAAAAAAAAAA0wAAAAAAAAB3AAAAAAAAABUBAAAAAAAADAIAAAAAAAAJAQAAAAAA
    AAcCAAAAAAAAOwEAAAAAAAChAQAAAAAAANkBAAAAAAAA9gEAAAAAAAA3AAAAAAAAAO8AAAAAAAAA
    XAEAAAAAAABNAQAAAAAAAI4AAAAAAAAAogAAAAAAAAC4AAAAAAAAAGYBAAAAAAAADwEAAAAAAADS
    AAAAAAAAACAAAAAAAAAAzQAAAAAAAAAeAQAAAAAAALsBAAAAAAAA9wAAAAAAAABTAQAAAAAAAG0B
    AAAAAAAA9gAAAAAAAAAQAQAAAAAAACUCAAAAAAAA+wAAAAAAAAAyAQAAAAAAAPoAAAAAAAAAYgEA
    AAAAAADtAQAAAAAAAGABAAAAAAAAzgAAAAAAAAAAAgAAAAAAACQCAAAAAAAAtQAAAAAAAACbAQAA
    AAAAALoBAAAAAAAAKQAAAAAAAAB1AAAAAAAAABgAAAAAAAAAfgAAAAAAAAC0AQAAAAAAAMgAAAAA
    AAAAtQEAAAAAAAAyAAAAAAAAAD0AAAAAAAAAKgAAAAAAAAAkAQAAAAAAAKoAAAAAAAAAmQEAAAAA
    AAC+AAAAAAAAAB8BAAAAAAAASAAAAAAAAAADAgAAAAAAABoAAAAAAAAAtgAAAAAAAAATAAAAAAAA
    ADoBAAAAAAAAowAAAAAAAABKAQAAAAAAANsAAAAAAAAAmgEAAAAAAAB3AQAAAAAAADcBAAAAAAAA
    FAIAAAAAAABNAAAAAAAAAHsAAAAAAAAARwEAAAAAAACWAAAAAAAAADABAAAAAAAAhgAAAAAAAACw
    AAAAAAAAACUBAAAAAAAAVAEAAAAAAABMAQAAAAAAAFYBAAAAAAAAAQEAAAAAAABqAQAAAAAAAMkA
    AAAAAAAALAAAAAAAAAB0AQAAAAAAACkCAAAAAAAASwEAAAAAAAAUAAAAAAAAAC0AAAAAAAAAWwEA
    AAAAAAA5AAAAAAAAAA0CAAAAAAAAsgAAAAAAAADsAAAAAAAAAMUAAAAAAAAANQEAAAAAAAD6AQAA
    AAAAAHEAAAAAAAAARAAAAAAAAACCAQAAAAAAANoAAAAAAAAAcgAAAAAAAADLAQAAAAAAANQBAAAA
    AAAAfwAAAAAAAACeAAAAAAAAAJYBAAAAAAAAmgAAAAAAAADjAQAAAAAAAAwAAAAAAAAAtgEAAAAA
    AADRAAAAAAAAAMIAAAAAAAAAJAAAAAAAAAB9AAAAAAAAAKAAAAAAAAAAggAAAAAAAABZAQAAAAAA
    AOkBAAAAAAAAngEAAAAAAAD+AQAAAAAAADkBAAAAAAAADAEAAAAAAABCAAAAAAAAAC4AAAAAAAAA
    ZQEAAAAAAACXAAAAAAAAAKwBAAAAAAAAcwEAAAAAAAAcAgAAAAAAADgAAAAAAAAA/QAAAAAAAAA2
    AQAAAAAAAIgAAAAAAAAASgAAAAAAAAD/AAAAAAAAABYCAAAAAAAAAwAAAAAAAACQAAAAAAAAAGwA
    AAAAAAAALQEAAAAAAAAbAgAAAAAAAEwAAAAAAAAAswEAAAAAAAAHAAAAAAAAAEkAAAAAAAAAFQIA
    AAAAAABIAQAAAAAAAH4BAAAAAAAA3wEAAAAAAADwAAAAAAAAAP0BAAAAAAAAWAEAAAAAAAAzAAAA
    AAAAABIBAAAAAAAAoQAAAAAAAAAVAAAAAAAAAJQAAAAAAAAAmAAAAAAAAABfAAAAAAAAAAkAAAAA
    AAAAnAEAAAAAAAAYAgAAAAAAAFcBAAAAAAAALQIAAAAAAADVAQAAAAAAAB0AAAAAAAAAHAEAAAAA
    AAAvAQAAAAAAAH0BAAAAAAAAiQAAAAAAAAADAQAAAAAAAMoBAAAAAAAAPAEAAAAAAABFAQAAAAAA
    AL4BAAAAAAAACgIAAAAAAAC9AAAAAAAAABkAAAAAAAAAQAEAAAAAAACAAAAAAAAAAFIBAAAAAAAA
    8gAAAAAAAAASAAAAAAAAAN4AAAAAAAAA3AAAAAAAAABBAAAAAAAAAJUBAAAAAAAAFAEAAAAAAACk
    AAAAAAAAABkCAAAAAAAA0QEAAAAAAADIAQAAAAAAAO8BAAAAAAAA2QAAAAAAAAA=
- 0
- !!python/tuple
  - 560
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
train_on_keys:
- bader
- total_energy
train_val_split: random
type_names:
- H
- Li
- Be
- B
- C
- N
- O
- F
- Na
- Mg
- Al
- Si
- P
- S
- Cl
- K
- Ca
- Sc
- Ti
- V
- Cr
- Mn
- Fe
- Co
- Ni
- Cu
- Zn
- Ga
- Ge
- As
- Se
- Br
- Rb
- Sr
- Y
- Zr
- Nb
- Mo
- Tc
- Ru
- Rh
- Pd
- Ag
- Cd
- In
- Sn
- Sb
- Te
- I
- Cs
- Ba
- La
- Ce
- Pr
- Nd
- Pm
- Sm
- Eu
- Gd
- Tb
- Dy
- Ho
- Er
- Tm
- Lu
- Hf
- Ta
- W
- Re
- Os
- Ir
- Pt
- Au
- Hg
- Tl
- Pb
- Bi
- Ac
- Th
- Pa
- U
- Np
- Pu
type_to_chemical_symbol:
  0: H
  1: Li
  2: Be
  3: B
  4: C
  5: N
  6: O
  7: F
  8: Na
  9: Mg
  10: Al
  11: Si
  12: P
  13: S
  14: Cl
  15: K
  16: Ca
  17: Sc
  18: Ti
  19: V
  20: Cr
  21: Mn
  22: Fe
  23: Co
  24: Ni
  25: Cu
  26: Zn
  27: Ga
  28: Ge
  29: As
  30: Se
  31: Br
  32: Rb
  33: Sr
  34: Y
  35: Zr
  36: Nb
  37: Mo
  38: Tc
  39: Ru
  40: Rh
  41: Pd
  42: Ag
  43: Cd
  44: In
  45: Sn
  46: Sb
  47: Te
  48: I
  49: Cs
  50: Ba
  51: La
  52: Ce
  53: Pr
  54: Nd
  55: Pm
  56: Sm
  57: Eu
  58: Gd
  59: Tb
  60: Dy
  61: Ho
  62: Er
  63: Tm
  64: Lu
  65: Hf
  66: Ta
  67: W
  68: Re
  69: Os
  70: Ir
  71: Pt
  72: Au
  73: Hg
  74: Tl
  75: Pb
  76: Bi
  77: Ac
  78: Th
  79: Pa
  80: U
  81: Np
  82: Pu
use_ema: false
use_sc: true
val_idcs: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
    ZQpxAVgJAAAAMTQ0NjgwMjg4cQJYAwAAAGNwdXEDS0VOdHEEUS6AAl1xAFgJAAAAMTQ0NjgwMjg4
    cQFhLkUAAAAAAAAAOQAAAAAAAAAwAAAAAAAAACQAAAAAAAAAMwAAAAAAAAAhAAAAAAAAACAAAAAA
    AAAABwAAAAAAAAAaAAAAAAAAABcAAAAAAAAAPwAAAAAAAAAsAAAAAAAAAAYAAAAAAAAAEwAAAAAA
    AAAtAAAAAAAAADcAAAAAAAAADgAAAAAAAAAUAAAAAAAAABkAAAAAAAAANQAAAAAAAAABAAAAAAAA
    AEEAAAAAAAAAKgAAAAAAAABCAAAAAAAAAEQAAAAAAAAACwAAAAAAAAAuAAAAAAAAAA0AAAAAAAAA
    OAAAAAAAAABAAAAAAAAAAAUAAAAAAAAAOgAAAAAAAAAxAAAAAAAAADsAAAAAAAAAHwAAAAAAAAA+
    AAAAAAAAADwAAAAAAAAADAAAAAAAAAApAAAAAAAAAAIAAAAAAAAAEQAAAAAAAAA2AAAAAAAAAD0A
    AAAAAAAAFQAAAAAAAAAjAAAAAAAAADIAAAAAAAAAAwAAAAAAAAAeAAAAAAAAAAAAAAAAAAAAKAAA
    AAAAAAAbAAAAAAAAAAkAAAAAAAAAQwAAAAAAAAAQAAAAAAAAABwAAAAAAAAADwAAAAAAAAAWAAAA
    AAAAABgAAAAAAAAAJQAAAAAAAAAiAAAAAAAAAAQAAAAAAAAACAAAAAAAAAASAAAAAAAAADQAAAAA
    AAAAHQAAAAAAAAAvAAAAAAAAACcAAAAAAAAAKwAAAAAAAAAKAAAAAAAAACYAAAAAAAAA
- 0
- !!python/tuple
  - 69
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
validation_batch_size: 5
validation_dataset: ase
validation_dataset_AtomicData_options:
  r_max: 5.0
validation_dataset_file_name: ../data/data_val.extxyz
var_num_neighbors: 12.11121940612793
verbose: INFO
wandb: true
wandb_project: bader charge
